<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>PsiOrleans.Orleans</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PsiOrleans.Common/PsiOrleans.Common.csproj" />
    <ProjectReference Include="../PsiOrleans.Specialized/PsiOrleans.Specialized.csproj" />
  </ItemGroup>
</Project> 