<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Psi.CliNew</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.CommandLine"/>
        <PackageReference Include="Microsoft.Orleans.Client"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console"/>
        <PackageReference Include="Aevatar.Core.Abstractions"/>
        <PackageReference Include="Aevatar.Core"/>
        <PackageReference Include="Aevatar"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Aevatar.Workshop.Client/Aevatar.Workshop.Client.csproj"/>
        <ProjectReference Include="..\PsiGAgent.Orchestrator\PsiGAgent.Orchestrator.csproj" />
        <ProjectReference Include="..\PsiGAgent.Specialized\PsiGAgent.Specialized.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
