<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aevatar.Core.Abstractions"/>
        <PackageReference Include="Aevatar.Core"/>
        <PackageReference Include="Aevatar.EventSourcing.Core"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PsiOrleans.Common\PsiOrleans.Common.csproj" />
      <ProjectReference Include="..\PsiOrleans.Specialized\PsiOrleans.Specialized.csproj" />
    </ItemGroup>

</Project>
