<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);SKEXP0001</NoWarn>
        <RootNamespace>PsiGAgent.Omni</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aevatar.Core.Abstractions" />
        <PackageReference Include="Aevatar.Core" />
        <PackageReference Include="Aevatar.EventSourcing.Core" />
        <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PsiGAgent.Common\PsiGAgent.Common.csproj" />
    </ItemGroup>
</Project>
